// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransactionDispatch.Infrastructure.Data;

#nullable disable

namespace TransactionDispatch.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDispatchDbContext))]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    partial class TransactionDispatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransactionDispatch.Infrastructure.Entities.DispatchJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteAfterSend")
                        .HasColumnType("boolean");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("FailedFiles")
                        .HasColumnType("integer");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuccessfulFiles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.ToTable("DispatchJobs");
                });

            modelBuilder.Entity("TransactionDispatch.Infrastructure.Entities.ProcessedFile", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("JobId", "FilePath");

                    b.ToTable("ProcessedFiles");
                });

            modelBuilder.Entity("TransactionDispatch.Infrastructure.Entities.ProcessedFile", b =>
                {
                    b.HasOne("TransactionDispatch.Infrastructure.Entities.DispatchJob", "Job")
                        .WithMany("ProcessedFileRecords")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TransactionDispatch.Infrastructure.Entities.DispatchJob", b =>
                {
                    b.Navigation("ProcessedFileRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
